### ISSUE TITLE
[BUG] Loosing connection with ATEM TVS HD after running >1h

### ISSUE THREAD

**Issue by Gartom** [bitfocus/companion-module-bmd-atem#168]
We have an issue with Companion loosing connection with our ATEM TVS HD after running for a while, typically ~1,5h. We are currently on build 3645 (i.e. not yet on latest bleeding edge build but will update as soon as possible).

Everything looks OK in the GUI when this happens and I can't  see any issues in the logs. The quick fix is to disable and enable the ATEM instance that gets everything up and running again. Normally, we only have Companion, an Arduino with Tally SW and a PC **or** a MAC running ATEM SW Control with connections to the ATEM TVS HD. We have been running the same setup for over a year and this issue seems to have starting to show up since the upgrade to build 3645. The last build we used before that was 3575.

**Comment by Gartom** [comment]
In today's ~3h session, we lost ability to communicate with the ATEM TVS HD twice. Both times it was solved by doing disable/enable of the ATEM instance (through a separate stream deck button). The issue seems to be triggered by doing some ATEM actions in ATEM SW Control on a Mac which gives me some hope to try to find a specific sequence that triggers the issue. BTW, Companion is not running on the Mac but on a separate PC.

**Comment by mark-epstein** [comment]
I don't know if it will help but I have had this sequence happen twice to me in the last couple months due to a loos AC power cord. For obvious reasons I don't want to experiment to try to verify the experience. Maybe this can help you investigate:

a. Power is very quicky lost and restored to the ATEM TVS HD
b. RPi can (maybe?) still communicate with the ATEM, but the ATEM software does not
c. Intentionally reboot the ATEM
d. RPi cannot communicate with the ATEM, ATEM software is fine
e. Repeat c-d numerous times, no change
f. Reboot RPi, no change
g. Reboot the stupid (i.e. non-managed, but also because I'm pretty frustrated at this point) switch that connects the RPi to the ATEM, everything works!

**Comment by Gartom** [comment]
This issue may be related: https://github.com/bitfocus/companion-module-ptzoptics-visca/issues/20

**Comment by obcocav** [comment]
Any update on this issue?  Running the latest stable 2.4.1 and losing connection to the ATEM TV STUDIO HD every so often.   Disable and reenable doesnt fix.  Have to disconnect ethernet and reconnect.

**Comment by Julusian** [comment]
I am hoping this is no longer an issue
